index:
    path: /
    controller: App\Controller\IndexController::index

get_categories:
    path: /categories
    controller: App\Controller\SearchController::getCategories

category_search:
    path: /search/category/{category}
    controller: App\Controller\SearchController::categorySearch

random_search:
    path: /search/random
    controller: App\Controller\SearchController::randomSearch

word_search:
    path: /search/{word}
    controller: App\Controller\SearchController::wordSearch

search_get_results:
    path: /search
    controller: App\Controller\SearchController::searchGetResults

mail_page:
    path: /mail
    controller: App\Controller\SearchController::mailPage
