<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWju098R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__ . '/ContainerWju098R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWju098R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWju098R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWju098R\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wju098R',
    'container.build_id' => '4ca990e7',
    'container.build_time' => 1641573899,
], __DIR__ . \DIRECTORY_SEPARATOR);
